import type { NoteStatsDisplay } from "../components/note-stats.js";
import type { TJAChart } from "../components/tja-chart.js";

export const tjaChart = document.getElementById("chart-component") as TJAChart;
export const statusDisplay = document.getElementById("status-display") as HTMLElement;
export const noteStatsDisplay = document.getElementById("note-stats-display") as NoteStatsDisplay;
export const languageSelector = document.getElementById("language-selector") as HTMLSelectElement;
export const difficultySelectorContainer = document.getElementById("difficulty-selector-container") as HTMLDivElement;
export const difficultySelector = document.getElementById("difficulty-selector") as HTMLSelectElement;
export const branchSelectorContainer = document.getElementById("branch-selector-container") as HTMLSpanElement;
export const branchSelector = document.getElementById("branch-selector") as HTMLSelectElement;
export const optionsCollapseBtn = document.getElementById("options-collapse-btn") as HTMLButtonElement;
export const optionsBody = document.getElementById("options-body") as HTMLDivElement;
export const appFooter = document.querySelector(".app-footer") as HTMLDivElement;
export const remoteConnectionStatus = document.getElementById("remote-connection-status") as HTMLDivElement;
export const remoteConnectionMsg = document.getElementById("remote-connection-msg") as HTMLDivElement;
export const remoteHostInput = document.getElementById("remote-host") as HTMLInputElement;
export const remotePortInput = document.getElementById("remote-port") as HTMLInputElement;
export const controlsContainer = document.getElementById("controls-container") as HTMLDivElement;
export const chartContainer = document.getElementById("chart-container") as HTMLDivElement;
export const layoutToggleBtn = document.getElementById("layout-toggle-btn") as HTMLButtonElement;
export const doTabs = document.querySelectorAll("#chart-options-panel .panel-tab");
export const doPanes = document.querySelectorAll("#chart-options-panel .panel-pane");
export const chartModeStatus = document.getElementById("chart-mode-status") as HTMLSpanElement;
export const dsTabs = document.querySelectorAll("#data-source-panel .panel-tab");
export const dsPanes = document.querySelectorAll("#data-source-panel .panel-pane");
export const dsCollapseBtn = document.getElementById("ds-collapse-btn") as HTMLButtonElement;
export const dsBody = document.getElementById("ds-body") as HTMLDivElement;
export const loadExampleBtn = document.getElementById("load-example-btn") as HTMLButtonElement;
export const tjaFilePicker = document.getElementById("tja-file-picker") as HTMLInputElement;
export const hostInput = document.getElementById("host-input") as HTMLInputElement;
export const portInput = document.getElementById("port-input") as HTMLInputElement;
export const connectBtn = document.getElementById("connect-btn") as HTMLButtonElement;
export const testStreamBtn = document.getElementById("test-stream-btn") as HTMLButtonElement;
export const eseSearchInput = document.getElementById("ese-search-input") as HTMLInputElement;
export const eseResults = document.getElementById("ese-results") as HTMLDivElement;
export const eseShareBtn = document.getElementById("ese-share-btn") as HTMLButtonElement;
