import { EseClient, type GitNode } from "../clients/ese-client.js";
import { exampleTJA } from "../core/example-data.js";
import { shareFile } from "../utils/file-share.js";
import { i18n } from "../utils/i18n.js";
import { JudgementClient, type ServerEvent } from "../clients/judgement-client.js";
import { NoteStatsDisplay } from "../components/note-stats.js";
import type { HitInfo, RenderTexts, ViewOptions } from "../core/renderer.js";
import { TJAChart } from "../components/tja-chart.js";
import { generateTJAFromSelection } from "../core/tja-exporter.js";
import { type ParsedChart, parseTJA } from "../core/tja-parser.js";

export const tjaChart = document.getElementById("chart-component") as TJAChart;
export const statusDisplay = document.getElementById("status-display") as HTMLElement;
export const noteStatsDisplay = document.getElementById("note-stats-display") as NoteStatsDisplay;
export const languageSelector = document.getElementById("language-selector") as HTMLSelectElement;
export const judgementWarning = document.getElementById("judgement-warning") as HTMLDivElement;
export const judgementControls = document.getElementById("judgement-controls") as HTMLDivElement;
export const judgementSubcontrols = document.getElementById("judgement-subcontrols") as HTMLDivElement;
export const judgementStyleRadios = document.querySelectorAll('input[name="judgementStyle"]');
export const judgementColoringRadios = document.querySelectorAll('input[name="judgementColoring"]');
export const showPerfectCheckbox = document.getElementById("show-perfect-checkbox") as HTMLInputElement;
export const showGoodCheckbox = document.getElementById("show-good-checkbox") as HTMLInputElement;
export const showPoorCheckbox = document.getElementById("show-poor-checkbox") as HTMLInputElement;
export const difficultySelectorContainer = document.getElementById("difficulty-selector-container") as HTMLDivElement;
export const difficultySelector = document.getElementById("difficulty-selector") as HTMLSelectElement;
export const branchSelectorContainer = document.getElementById("branch-selector-container") as HTMLSpanElement;
export const branchSelector = document.getElementById("branch-selector") as HTMLSelectElement;
export const collapseLoopCheckbox = document.getElementById("collapse-loop-checkbox") as HTMLInputElement;
export const optionsCollapseBtn = document.getElementById("options-collapse-btn") as HTMLButtonElement;
export const optionsBody = document.getElementById("options-body") as HTMLDivElement;
export const showStatsCheckbox = document.getElementById("show-stats-checkbox") as HTMLInputElement;
export const loopControls = document.getElementById("loop-controls") as HTMLDivElement;
export const loopAutoCheckbox = document.getElementById("loop-auto") as HTMLInputElement;
export const loopPrevBtn = document.getElementById("loop-prev") as HTMLButtonElement;
export const loopNextBtn = document.getElementById("loop-next") as HTMLButtonElement;
export const loopCounter = document.getElementById("loop-counter") as HTMLSpanElement;
export const zoomOutBtn = document.getElementById("zoom-out-btn") as HTMLButtonElement;
export const zoomInBtn = document.getElementById("zoom-in-btn") as HTMLButtonElement;
export const zoomResetBtn = document.getElementById("zoom-reset-btn") as HTMLButtonElement;
export const appFooter = document.querySelector(".app-footer") as HTMLDivElement;
export const changelogBtn = document.getElementById("changelog-btn") as HTMLButtonElement;
export const changelogModal = document.getElementById("changelog-modal") as HTMLDivElement;
export const changelogList = document.getElementById("changelog-list") as HTMLDivElement;
export const controlsContainer = document.getElementById("controls-container") as HTMLDivElement;
export const chartContainer = document.getElementById("chart-container") as HTMLDivElement;
export const layoutToggleBtn = document.getElementById("layout-toggle-btn") as HTMLButtonElement;
export const doTabs = document.querySelectorAll("#chart-options-panel .panel-tab");
export const doPanes = document.querySelectorAll("#chart-options-panel .panel-pane");
export const clearSelectionBtn = document.getElementById("clear-selection-btn") as HTMLButtonElement;
export const exportSelectionBtn = document.getElementById("export-selection-btn") as HTMLButtonElement;
export const exportChartNameInput = document.getElementById("export-chart-name") as HTMLInputElement;
export const clearAnnotationsBtn = document.getElementById("clear-annotations-btn") as HTMLButtonElement;
export const autoAnnotateBtn = document.getElementById("auto-annotate-btn") as HTMLButtonElement;
export const chartModeStatus = document.getElementById("chart-mode-status") as HTMLSpanElement;
export const dsTabs = document.querySelectorAll("#data-source-panel .panel-tab");
export const dsPanes = document.querySelectorAll("#data-source-panel .panel-pane");
export const dsCollapseBtn = document.getElementById("ds-collapse-btn") as HTMLButtonElement;
export const dsBody = document.getElementById("ds-body") as HTMLDivElement;
export const loadExampleBtn = document.getElementById("load-example-btn") as HTMLButtonElement;
export const tjaFilePicker = document.getElementById("tja-file-picker") as HTMLInputElement;
export const hostInput = document.getElementById("host-input") as HTMLInputElement;
export const portInput = document.getElementById("port-input") as HTMLInputElement;
export const connectBtn = document.getElementById("connect-btn") as HTMLButtonElement;
export const testStreamBtn = document.getElementById("test-stream-btn") as HTMLButtonElement;
export const eseSearchInput = document.getElementById("ese-search-input") as HTMLInputElement;
export const eseResults = document.getElementById("ese-results") as HTMLDivElement;
export const eseShareBtn = document.getElementById("ese-share-btn") as HTMLButtonElement;
