import type { ChartListPanel } from "../components/chart-list-panel.js";
import "../components/course-branch-select.js"; // Ensure custom element is defined
import type { CourseBranchSelect } from "../components/course-branch-select.js";
import type { NoteStatsDisplay } from "../components/note-stats.js";
import type { TJAChart } from "../components/tja-chart.js";

export const tjaChart = document.getElementById("chart-component") as TJAChart;
export const statusDisplay = document.getElementById("status-display") as HTMLElement;
export const noteStatsDisplay = document.getElementById("note-stats-display") as NoteStatsDisplay;
export const languageSelector = document.getElementById("language-selector") as HTMLSelectElement;
export const courseBranchSelect = document.getElementById("course-branch-select") as CourseBranchSelect;
export const optionsCollapseIcon = document.getElementById("options-collapse-icon") as HTMLImageElement;
export const optionsPanelHeader = document.getElementById("options-panel-header") as HTMLDivElement;
export const optionsBody = document.getElementById("options-body") as HTMLDivElement;
export const appFooter = document.querySelector(".app-footer") as HTMLDivElement;
export const remoteConnectionStatus = document.getElementById("remote-connection-status") as HTMLDivElement;
export const remoteConnectionMsg = document.getElementById("remote-connection-msg") as HTMLDivElement;
export const remoteHostInput = document.getElementById("remote-host") as HTMLInputElement;
export const remotePortInput = document.getElementById("remote-port") as HTMLInputElement;
export const controlsContainer = document.getElementById("controls-container") as HTMLDivElement;
export const chartContainer = document.getElementById("chart-container") as HTMLDivElement;
export const layoutToggleBtn = document.getElementById("layout-toggle-btn") as HTMLButtonElement;
export const doTabs = document.querySelectorAll("#chart-options-panel .panel-tab");
export const doPanes = document.querySelectorAll("#chart-options-panel .panel-pane");
export const chartModeStatus = document.getElementById("chart-mode-status") as HTMLSpanElement;
export const dsTabs = document.querySelectorAll("#data-source-panel .panel-tab");
export const dsPanes = document.querySelectorAll("#data-source-panel .panel-pane");
export const dsCollapseIcon = document.getElementById("ds-collapse-icon") as HTMLImageElement;
export const dsPanelHeader = document.getElementById("ds-panel-header") as HTMLDivElement;
export const dsBody = document.getElementById("ds-body") as HTMLDivElement;
export const hostInput = document.getElementById("host-input") as HTMLInputElement;
export const portInput = document.getElementById("port-input") as HTMLInputElement;
export const connectBtn = document.getElementById("connect-btn") as HTMLButtonElement;
export const testStreamBtn = document.getElementById("test-stream-btn") as HTMLButtonElement;
export const chartListPanel = document.getElementById("chart-list-panel") as ChartListPanel;
